-- MySQL Script generated by MySQL Workbench
-- Fri May 24 18:03:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dem` DEFAULT CHARACTER SET utf8 ;
USE `dem` ;

-- -----------------------------------------------------
-- Table `dem`.`DataUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dem`.`DataUser` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `passsword` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dem`.`MasterUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dem`.`MasterUser` (
  `masterID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `passsword` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`masterID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dem`.`DataRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dem`.`DataRequests` (
  `requestID` INT(11) NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `computerTechType` VARCHAR(45) NOT NULL,
  `computerTechModel` VARCHAR(45) NOT NULL,
  `problemDescryption` VARCHAR(45) NOT NULL,
  `requestStatus` VARCHAR(45) NOT NULL,
  `completionDate` DATE NULL DEFAULT NULL,
  `masterID` INT(11) NULL DEFAULT NULL,
  `clientID` INT(11) NOT NULL,
  PRIMARY KEY (`requestID`, `masterID`, `clientID`),
  INDEX `fk_Zavka_User1_idx` (`clientID` ASC) ,
  INDEX `fk_zavka_MasterUser1_idx` (`masterID` ASC) ,
  CONSTRAINT `fk_Zavka_User1`
    FOREIGN KEY (`clientID`)
    REFERENCES `dem`.`DataUser` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zavka_MasterUser1`
    FOREIGN KEY (`masterID`)
    REFERENCES `dem`.`MasterUser` (`masterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dem`.`DataComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dem`.`DataComments` (
  `commentID` INT(11) NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(45) NOT NULL,
  `masterID` INT(11) NOT NULL,
  `requestID` INT(11) NOT NULL,
  PRIMARY KEY (`commentID`, `masterID`, `requestID`),
  INDEX `fk_DataComments_DataRequests1_idx` (`requestID` ASC, `masterID` ASC) ,
  CONSTRAINT `fk_DataComments_DataRequests1`
    FOREIGN KEY (`requestID` , `masterID`)
    REFERENCES `dem`.`DataRequests` (`requestID` , `masterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
